In [1]:
import pandas as pd
import numpy as np

# MULTI DIM NORMAL

In [2]:
df = pd.DataFrame({
...                   'X1': [1.5,2.2,3.9,2.1,0.5,0.9,2.7,2.5,2.8,0.1],
...                   'X2': [4.5,1.5,3.4,2.9,3.2,4.3,2.1,3.5,4.9,3.7]
}
...                  )

In [3]:
df_nump = df.to_numpy()

In [4]:
df_nump

array([[1.5, 4.5],
       [2.2, 1.5],
       [3.9, 3.4],
       [2.1, 2.9],
       [0.5, 3.2],
       [0.9, 4.3],
       [2.7, 2.1],
       [2.5, 3.5],
       [2.8, 4.9],
       [0.1, 3.7]])

In [5]:
cov = [[1, 0], [0, 1]]

In [6]:
mean = [[0.5,4.2], [2.4,1.6], [3,3.2]]

In [7]:
import matplotlib.pyplot as plt
from scipy.stats import multivariate_normal
f1 = multivariate_normal.pdf(df_nump, mean=mean[0], cov=cov)
f1

array([0.09228469, 0.00098008, 0.00035696, 0.01900835, 0.09653235,
       0.14618577, 0.0015603 , 0.01685889, 0.00884523, 0.12965515])

# 1 D normal dist

In [62]:
df = pd.DataFrame({
...                   'X': [25.1,20.7,24.3,19.4,31.9,15.0]
}
...                  )

In [63]:
# var = 102
# m = 22

In [67]:
df['X'].var(ddof=0)

27.855555555555554

In [68]:
df['X'].mean()

22.733333333333334

In [69]:
df2 = pd.DataFrame({
...                   'X': [14.4,12.4,17.6,18.1]
}
...                  )

In [70]:
df2['X'].mean()

15.625000000000002

In [71]:
df2['X'].var(ddof=0)

5.481875000000002

In [72]:
# import required libraries
from scipy.stats import norm

In [73]:
# norm.pdf([25,20,14,24,12,44,15])

In [74]:
# mean 100 and standard deviation 15
from scipy import stats
normal=stats.norm(loc=100, scale=15)

In [75]:
print(normal.pdf([120,130,140]))

[0.010934   0.0035994  0.00075973]


In [92]:
# for df
normal=stats.norm(loc=df['X'].mean(), scale=df['X'].std(ddof=0))

In [93]:
print(normal.pdf([25.1,20.7,24.3,19.4,31.9,15.0]))

[0.06835824 0.07018175 0.07233036 0.06192097 0.01672699 0.02583748]


In [94]:
print(normal.pdf([23.2]))

[0.07529332]


In [95]:
# for df2
normal=stats.norm(loc=df2['X'].mean(), scale=df2['X'].std(ddof=0))

In [96]:
print(normal.pdf([14.4,12.4,17.6,18.1]))

[0.14859458 0.06598686 0.11938081 0.09745365]


In [97]:
print(normal.pdf([23.2]))

[0.00090885]


In [98]:
normal.pdf([23])

array([0.0011938])

# KDE

In [60]:
from numpy import array, linspace
# s = linspace(1,20)
df_kde = pd.DataFrame({'Xj': [-0.5,2.5,3.5,4.5,6.5,7.5,10.5,13.5,16.5]})
# df_kde = pd.DataFrame(s,columns = ['Xj'])
df_kde['1_z'] = abs((df_kde['Xj']-1)/3)
df_kde['1_k'] = df_kde['1_z'].apply(lambda x: 0 if x > 0.5 else 1)
df_kde['5_z'] = abs((df_kde['Xj']-5)/3)
df_kde['5_k'] = df_kde['5_z'].apply(lambda x: 0 if x > 0.5 else 1)
df_kde['6_z'] = abs((df_kde['Xj']-6)/3)
df_kde['6_k'] = df_kde['6_z'].apply(lambda x: 0 if x > 0.5 else 1)
df_kde['9_z'] = abs((df_kde['Xj']-9)/3)
df_kde['9_k'] = df_kde['9_z'].apply(lambda x: 0 if x > 0.5 else 1)
df_kde['15_z'] = abs((df_kde['Xj']-15)/3)
df_kde['15_k'] = df_kde['15_z'].apply(lambda x: 0 if x > 0.5 else 1)
df_kde['k_sum'] = (df_kde['1_k'] + df_kde['5_k'] + df_kde['6_k'] + df_kde['9_k'] + df_kde['15_k'])
df_kde['kde'] = (df_kde['1_k'] + df_kde['5_k'] + df_kde['6_k'] + df_kde['9_k'] + df_kde['15_k'])/15
df_kde

Xj       1_z  1_k       5_z  5_k       6_z  6_k       9_z  9_k      15_z  \
0  -0.5  0.500000    1  1.833333    0  2.166667    0  3.166667    0  5.166667   
1   2.5  0.500000    1  0.833333    0  1.166667    0  2.166667    0  4.166667   
2   3.5  0.833333    0  0.500000    1  0.833333    0  1.833333    0  3.833333   
3   4.5  1.166667    0  0.166667    1  0.500000    1  1.500000    0  3.500000   
4   6.5  1.833333    0  0.500000    1  0.166667    1  0.833333    0  2.833333   
5   7.5  2.166667    0  0.833333    0  0.500000    1  0.500000    1  2.500000   
6  10.5  3.166667    0  1.833333    0  1.500000    0  0.500000    1  1.500000   
7  13.5  4.166667    0  2.833333    0  2.500000    0  1.500000    0  0.500000   
8  16.5  5.166667    0  3.833333    0  3.500000    0  2.500000    0  0.500000   

   15_k  k_sum       kde  
0     0      1  0.066667  
1     0      1  0.066667  
2     0      1  0.066667  
3     0      2  0.133333  
4     0      2  0.133333  
5     0      2  0.133333  
6     0      1  0.066667  
7     1      1  0.066667  
8     1      1  0.066667

In [61]:
# from matplotlib.pyplot import plot

# kde_np = df_kde['kde'].to_numpy()
# vals = df_kde['Xj'].to_numpy()
# plot(vals, kde_np)

In [100]:
(2+3+4+5)/4

3.5

(6+10+14)/3

In [101]:
(6+10+14)/3

10.0

In [103]:
df = pd.DataFrame({
...                   'X': [2,3,4,5,6,10,14]
}
...                  )

In [104]:
df['X-3.5']=df['X']-3.5

In [105]:
df['X-10']=df['X']-10

In [106]:
df

X  X-3.5  X-10
0   2   -1.5    -8
1   3   -0.5    -7
2   4    0.5    -6
3   5    1.5    -5
4   6    2.5    -4
5  10    6.5     0
6  14   10.5     4

In [107]:
(2+3+4+5+6)/5

4.0

In [108]:
(10+14)/2

12.0

In [109]:
df['X-4']=df['X']-4

In [110]:
df['X-12']=df['X']-12

In [111]:
df

X  X-3.5  X-10  X-4  X-12
0   2   -1.5    -8   -2   -10
1   3   -0.5    -7   -1    -9
2   4    0.5    -6    0    -8
3   5    1.5    -5    1    -7
4   6    2.5    -4    2    -6
5  10    6.5     0    6    -2
6  14   10.5     4   10     2

In [112]:
(2+3)/2

2.5

In [113]:
(4+5+6+10+14)/5

7.8

In [117]:
df = pd.DataFrame({
...                   'X': [2,3,4,5,6,10,14]
}
...                  )

In [119]:
df['X-2.5']=df['X']-2.5

In [120]:
df['X-7.8']=df['X']-7.8

In [121]:
df

X  X-2.5  X-7.8
0   2   -0.5   -5.8
1   3    0.5   -4.8
2   4    1.5   -3.8
3   5    2.5   -2.8
4   6    3.5   -1.8
5  10    7.5    2.2
6  14   11.5    6.2